// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjbphjykaltakrmwaqec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqYnBoanlrYWx0YWtybXdhcWVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxODIyOTYsImV4cCI6MjA2NTc1ODI5Nn0.CIqIheNGEO3SwBZ0eUMWb1i3oIayDzi8N7hCWc_JzY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);